#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bit285-registartion-db")]
public partial class LinqToDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUserData(UserData instance);
  partial void UpdateUserData(UserData instance);
  partial void DeleteUserData(UserData instance);
  #endregion
	
	public LinqToDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bit285_registartion_dbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinqToDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqToDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqToDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqToDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<UserData> UserDatas
	{
		get
		{
			return this.GetTable<UserData>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserData")]
public partial class UserData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _userID;
	
	private string _firstName;
	
	private string _lastName;
	
	private System.Nullable<bool> _emailUpdates;
	
	private string _email;
	
	private string _userName;
	
	private string _password;
	
	private System.Nullable<System.DateTime> _lastLogin;
	
	private System.Nullable<int> _programID;
	
	private bool _loggedIn;
	
	private string _ipAddress;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnemailUpdatesChanging(System.Nullable<bool> value);
    partial void OnemailUpdatesChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnlastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnlastLoginChanged();
    partial void OnprogramIDChanging(System.Nullable<int> value);
    partial void OnprogramIDChanged();
    partial void OnloggedInChanging(bool value);
    partial void OnloggedInChanged();
    partial void OnipAddressChanging(string value);
    partial void OnipAddressChanged();
    #endregion
	
	public UserData()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int userID
	{
		get
		{
			return this._userID;
		}
		set
		{
			if ((this._userID != value))
			{
				this.OnuserIDChanging(value);
				this.SendPropertyChanging();
				this._userID = value;
				this.SendPropertyChanged("userID");
				this.OnuserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string firstName
	{
		get
		{
			return this._firstName;
		}
		set
		{
			if ((this._firstName != value))
			{
				this.OnfirstNameChanging(value);
				this.SendPropertyChanging();
				this._firstName = value;
				this.SendPropertyChanged("firstName");
				this.OnfirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string lastName
	{
		get
		{
			return this._lastName;
		}
		set
		{
			if ((this._lastName != value))
			{
				this.OnlastNameChanging(value);
				this.SendPropertyChanging();
				this._lastName = value;
				this.SendPropertyChanged("lastName");
				this.OnlastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUpdates", DbType="Bit")]
	public System.Nullable<bool> emailUpdates
	{
		get
		{
			return this._emailUpdates;
		}
		set
		{
			if ((this._emailUpdates != value))
			{
				this.OnemailUpdatesChanging(value);
				this.SendPropertyChanging();
				this._emailUpdates = value;
				this.SendPropertyChanged("emailUpdates");
				this.OnemailUpdatesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLogin", DbType="DateTime")]
	public System.Nullable<System.DateTime> lastLogin
	{
		get
		{
			return this._lastLogin;
		}
		set
		{
			if ((this._lastLogin != value))
			{
				this.OnlastLoginChanging(value);
				this.SendPropertyChanging();
				this._lastLogin = value;
				this.SendPropertyChanged("lastLogin");
				this.OnlastLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programID", DbType="Int")]
	public System.Nullable<int> programID
	{
		get
		{
			return this._programID;
		}
		set
		{
			if ((this._programID != value))
			{
				this.OnprogramIDChanging(value);
				this.SendPropertyChanging();
				this._programID = value;
				this.SendPropertyChanged("programID");
				this.OnprogramIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loggedIn", DbType="Bit NOT NULL")]
	public bool loggedIn
	{
		get
		{
			return this._loggedIn;
		}
		set
		{
			if ((this._loggedIn != value))
			{
				this.OnloggedInChanging(value);
				this.SendPropertyChanging();
				this._loggedIn = value;
				this.SendPropertyChanged("loggedIn");
				this.OnloggedInChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipAddress", DbType="NVarChar(50)")]
	public string ipAddress
	{
		get
		{
			return this._ipAddress;
		}
		set
		{
			if ((this._ipAddress != value))
			{
				this.OnipAddressChanging(value);
				this.SendPropertyChanging();
				this._ipAddress = value;
				this.SendPropertyChanged("ipAddress");
				this.OnipAddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
